# main.yml

- name: Set up Mac
  hosts: localhost
  vars:
    install_homebrew_if_missing: True

  tasks:
    - import_tasks: ./tasks/homebrew.yml
    - import_tasks: ./tasks/install_asdf.yml
    - import_tasks: ./tasks/setup_prezto.yml
    - import_tasks: ./tasks/install_nvm.yml
    - import_tasks: ./tasks/install_node.yml
    - import_tasks: ./tasks/setup_python.yml
    - import_tasks: ./tasks/install_rust.yml

