---
- name: Check if Rust is already installed
  command: rustc --version
  register: rust_installed
  ignore_errors: yes

- name: Download and install Rust
  shell: |
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
  args:
    creates: "{{ ansible_env.HOME }}/.cargo/bin/rustc"
  environment:
    - CARGO_HOME: "{{ ansible_env.HOME }}/.cargo"
    - RUSTUP_HOME: "{{ ansible_env.HOME }}/.rustup"
  when: rust_installed.rc != 0

- name: Ensure Cargo bin directory is in PATH
  lineinfile:
    path: "{{ ansible_env.HOME }}/.zshenv"
    line: 'export PATH="$HOME/.cargo/bin:$PATH"'
    state: present
  when: rust_installed.rc != 0

- name: Reload .zshenv if Rust was just installed
  shell: source "{{ ansible_env.HOME }}/.zshenv"
  args:
    executable: /bin/zsh
  when: rust_installed.rc != 0
