# Step 1: Ensure Zprezto is installed
- name: Check if Zprezto is installed
  stat:
    path: "{{ ansible_env.HOME }}/.zprezto"
  register: zprezto_dir

- name: Clone Zprezto repository
  git:
    repo: https://github.com/sorin-ionescu/prezto.git
    dest: "{{ ansible_env.HOME }}/.zprezto"
  when: not zprezto_dir.stat.exists

- name: Check if .zshrc is exist
  stat:
    path: "{{ ansible_env.HOME }}/.zshrc"
  register: zshrc

- name: Ensure .zshrc file exists
  file:
    path: "{{ ansible_env.HOME }}/.zshrc"
    state: touch
    mode: '0644'
  when: not zshrc.stat.exists

- name: Add Prezto initialization line to .zshrc
  lineinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    line: 'source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"'
    state: present
    insertafter: EOF
    backup: yes

# Step 2: Get Oh My Zsh plugins
- name: Ensure Oh My Zsh plugins directory exists
  stat:
    path: "{{ ansible_env.HOME }}/.oh-my-zsh/plugins"
  register: ohmyzsh_dir

- name: Clone the asdf plugin from Oh My Zsh
  git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh"
    depth: 1
  when: not ohmyzsh_dir.stat.exists

- name: Update Oh My Zsh repository
  git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: ~/.oh-my-zsh
    update: yes
  when: ohmyzsh_dir.stat.exists

# Step 3: Create a custom Zprezto module Oh My ZSH plugins
- name: Check if .zshrc is exist
  stat:
    path: "{{ ansible_env.HOME }}/.zshrc"
  register: zprezto_contrib

- name: Create custom Zprezto module directory
  file:
    path: "{{ ansible_env.HOME }}/.zprezto-contrib"
    state: directory
    mode: '0755'
  when: not zprezto_contrib.stat.exists

- name: Copy selected Oh My Zsh plugins to zprezto-contrib
  copy:
    src: "{{ ansible_env.HOME }}/.oh-my-zsh/plugins/{{ item }}"
    dest: "{{ ansible_env.HOME }}/.zprezto-contrib/"
    remote_src: yes
  with_items:
    - asdf

- name: Replace .zpreztorc from config folder
  copy:
    src: ./configs/zsh/zpreztorc
    dest: ~/.zprezto/runcoms/zpreztorc
    remote_src: yes
    force: yes

# Step 4: Restart Zsh
- name: Reload ZSH
  shell: source "{{ ansible_env.HOME }}/.zshrc"
  args:
    executable: /bin/zsh
